### ISSUE TITLE
Should random primitives have APL/BQN-like symbols?

### ISSUE THREAD

**Issue by vegabook** [mlochbaum/BQN#20]
I am very new to APL/BQN and am very enamoured with your project, which, after many months of hunting down which programming language I was going to learn next, finally your pitch has seduced me 🛸. Very exciting. 

I have one comment though. With the increasing growth of probabilistic programming languages and libraries, and with the huge importance of random number generation in machine learning, would it be worthwhile to extend the BQN symbol set with random number primimives, as opposed to the keywords currently proposed?

It seems to me that an even larger part of mathematical and statistical programming in the future will deal with randomness and this might help the concept of the notation as a tool of thought?

Am I right that Dyalog APL has `?` as a symbol for "roll", for example? I don't seem to be able to find it in BQN.

**Comment by mlochbaum** [comment]
You're right that most APLs use `?` for random number generation. I removed it in BQN and instead have defined [system values](https://mlochbaum.github.io/BQN/spec/system.html#random-generation) to deal with random numbers, which are currently supported in CBQN. For example the common APL pattern `?4⍴6` would be written `4 •rand.Range 6`.

The biggest reason not to make `?` a primitive is that pseudorandom generation is stateful, and primitives in BQN are always stateless. Because BQN has the function `•MakeRand` to *create* a generator, it gives you much better control over the state, where APL uses `⎕RL` to control the state, which doesn't scale well. With `•MakeRand` different parts of a program can have their own non-interfering generators. Depending on what it does, a tool might always use its own generator (possibly recording the seed), require the user to supply one, or use its own by default but allow the caller to override it. The fact that it's a namespace also allows us to easily add all sorts of distributions and special functions without having to make new primitives.

For areas where random generation is a central part of programming, `•ReBQN` ([draft spec](https://mlochbaum.github.io/BQN/spec/system.html#execution)) would allow you to extend BQN with appropriate primitives. Something like the following. But right now only CBQN has `•MakeRand` and only the online REPL supports `primitives⇐`, so you can't run this code anywhere yet.

```
rand ← •MakeRand 1  # Initialize
bqn_rand ← •ReBQN {primitives⇐•primitives∾⟨⟨'?',rand.Range⚇0⊘rand.Deal⟩⟩}
BQN_rand "3?5"
```

**Comment by mlochbaum** [comment]
If you get stuck on another primitives, the [BQN-Dyalog dictionary](https://mlochbaum.github.io/BQN/doc/fromDyalog.html#for-writing) has most of them. For `?` it does point you to `•MakeRand`, although `•rand` would be more accurate now that it exists (added to CBQN three days ago).

**Comment by mlochbaum** [comment]
Added `•rand` to the online REPL, so defining `?` [now works](https://mlochbaum.github.io/BQN/try.html#code=cmFuZCDihpAg4oCicmFuZApicW5fcmFuZCDihpAg4oCiUmVCUU4ge3ByaW1pdGl2ZXPih5DigKJwcmltaXRpdmVz4oi+4p+o4p+oJz8nLHJhbmQuUmFuZ2Ximocw4oqYcmFuZC5EZWFs4p+p4p+pfQpCUU5fcmFuZCAiMz81Ig==). `•MakeRand` would be harder because it can't use `Math.random()`, as that can't be initialized.

**Comment by vegabook** [comment]
Thanks understood. Makes sense. I'l continue the second few steps into my BQN adventure!

**Comment by vegabook** [comment]
Yeah giving this some more thought it does seem correct that any "primitive" that relies on a seed is no longer a primitive. Therefore this choice actually makes BQN purer in a mathematical sense. 

I guess I'm (probably vainly) loving the idea of primitive symbols; as one of my (super hot C++ programmer) friends at a big hedge fund was saying about APL "wow this his hieroglyphics" and that was a compliment! Haha. Anyway all good thanks for the explanation.
