### ISSUE TITLE
3 √ 729 returns float not integer

### ISSUE THREAD

**Issue by doyougnu** [mlochbaum/BQN#37]
Hello, I noticed the following when working on a documentation major mode for emacs. I'm unsure if its a bug, or intended due to some floating point standard.

Consider:
```
9 ⋆ 3

   729
```

But:
```
3 √ 729

   8.999999999999998
```

and
```
0‿1‿2‿3 √ 729‿729‿729‿729 

   ⟨ ∞ 729 27 8.999999999999998 ⟩
```

So sometimes `√` returns a float even though 729 has a integer cube root.

The next lowest natural number that has both an integer square root and cube root is 64, notice that we get integers back rather than floats:
```
0‿1‿2‿3 √ 64‿64‿64‿64

   ⟨ ∞ 64 8 4 ⟩
```

For what its worth `numpy` only returns a floats, although offset in the opposite direction:
```
Python 3.8.2 (default, Feb 26 2020, 02:56:10)
>>> import numpy as np
>>> np.cbrt(8)
2.0
>>> np.cbrt(64)
4.0
>>> np.cbrt(729)
9.000000000000002
```

**Comment by mlochbaum** [comment]
`√` doesn't distinguish between floats and integers (nor does any other arithmetic function) and shouldn't be assumed to return exact results.

The problem here is that `𝕨√𝕩` is computed as `𝕩⋆÷𝕨`, that is, two separate operations. `÷3` happens to round down, so the exponent in `729⋆÷3` is too low, and the result ends up rounding down again even though it is fairly accurate. Recently I wrote a [script](https://github.com/mlochbaum/Singeli/blob/master/num.bqn) for higher-precision arithmetic using pairs of floats and was able to confirm with this that `×´ 729 ⋆ 1‿0 Div 3‿0` is exactly 9. The result of `Div` is `⟨0.333…, 1.850…e¯17⟩` indicating that the more precise reciprocal is slightly larger than the double-precision rounded version given by the first element.

Programming languages typically give access to the [functions](https://en.wikipedia.org/wiki/C_mathematical_functions) defined by the C standard library, which has a square root and cube root (probably what numpy's using) but no general root function. Exponentiation is numerically complicated, so that implementing a general root would be a significant challenge. And since BQN aims to be portable, a requirement for high precision across many implementations would make life hard for implementers. We will probably consider making CBQN's `√` more accurate at some point but the result you showed is not considered a bug.
