### ISSUE TITLE
Keyboard special character map

### ISSUE THREAD

**Issue by jackokring** [mlochbaum/BQN#39]
is https://mlochbaum.github.io/BQN/keymap.html correct and up to date?

I'm doing https://github.com/jackokring/qmk_firmware/tree/master/keyboards/dz60/keymaps/jacko_keys to make a BQN pair of key layers.

I noticed ⍎⍕↙↖⍳ are marked as both possibly removed but also possibly going to be added.

**Comment by mlochbaum** [comment]
Yes, I'm fairly sure it's correct. The keys `⍎⍕↙↖⍳` are definitely on the keyboard: the page says they're not used by the *language*. There isn't much of a reason to keep them there (except `⍳`; see below) but also no real reason to take them off.

I think `⍳` will most likely be defined in the future, for BQN implementations that support complex numbers (there aren't any of these yet). It would be the [Complex](https://code.jsoftware.com/wiki/Vocabulary/jdot) function from J, which multiplies `𝕩` by i, then adds `𝕨` if given. Other than that, there aren't any candidates for new primitives, so the required set of characters will probably stay as it is for a long time.

**Comment by jackokring** [comment]
OK, as I think I will put the code points in the keyboard programming file (inc  ⍳ ). It fits with 748 bytes of firmware left (the code points are 32-bit zeros to test). I managed to fit a macro layer and a few extra shift planes in, so plenty of expandability from cheap dz60 ASCII boards.

**Comment by jackokring** [comment]
Ok, placed chars in. Space left for some combination of 4 more overlay layers (11 shiftable unicode chars, ~14 unshiftables, not including all the blanks on the BQN layer, default is 12 bit character code for no extra memory), light options and/or ...?

**Comment by jackokring** [comment]
Wondering if Unicode 2bd1 might represent NaN and ERROR and be like a constant on unshifted 7 key next to infinity?

**Comment by mlochbaum** [comment]
The strategy in BQN is not so much to add characters when they could represent something, but to pick the functionality that's most fundamental and important for programming and assign characters to that. There's a pretty high cost to adding a character because people have to learn it and how to type it, and fonts have to support it. For NaN, we're even considering removing support from CBQN and I don't think the cost is close to being justified.

If you're trying to fill up the keyboard (I don't know why this would be a goal) then I'd probably suggest adding APL and mathematical symbols that users might want to extend BQN with, like `⊂⊃⊆⊇∩∪⊥⊤⊕⊗`. More APL characters shown in the first table in the [fonts page](https://mlochbaum.github.io/BQN/fonts.html), and the [Mathematical Operators](https://en.wikipedia.org/wiki/Mathematical_Operators) block has some commonly used characters in math as well.

**Comment by jackokring** [comment]
That's cool. I was expecting "strong zero" and no NaN. I've got much key codes to fill with my randoms, and so the BQN layer is best as is necessary to the design of the language.

It was more a "Inf" seems to have a char but NaN didn't.
