### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by bijang** [mlochbaum/BQN#42]
Fantastic project, is there a roadmap for this, or milestones, or release tag as milestone?

**Comment by mlochbaum** [comment]
There's the "will provide" list on the front page, and possible core language changes are tracked [here](https://topanswers.xyz/apl?q=1888). We almost never make time estimates as they usually turn out to be wrong. And implementations like CBQN aren't versioned because there's no development cycle that would distinguish one commit from any other.
