### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by oraqlle** [mlochbaum/BQN#43]
I'm a little confused at how to get BQN up and running on Linux using CBQN, I don't know what I'm reading wrong or if there is something I'm missing. How am I supposed to get this up and running. I'm on WSL Ubuntu if that is any help. I'm am really interesting in this language and notational/array based syntax and semantics as a whole and any help would be greatly appreciated.

**Comment by oraqlle** [comment]
I cloned the repo and compiled using make but I tried running the test 
`./BQN mlochbaum/BQN/test/this.bqn` 
and I got the following output 
`Error: Couldn't read file "mlochbaum/BQN/test/this.bqn"`. 
I don't know if I've installed something wrong or if the file is remote.

**Comment by mlochbaum** [comment]
`mlochbaum/BQN` just refers to this repository so you need to clone it and use the correct path (if `ls` works but `./BQN` doesn't, then I'd be quite surprised). But since you've built you should already have a working system, which you can test out with say `./BQN --help` and `./BQN -p "↕5"`. The tests only check that it works.
