### ISSUE TITLE
Hovering on Scan in the online REPL does not show input help

### ISSUE THREAD

**Issue by miguelraz** [mlochbaum/BQN#59]
Hi!
BQN rocks!
----
If I hover over `Fold`, I get `Fold \5`, but if I hover over `Scan` I get only `Scan`, without the helpful tip for `\`` to be included.

I tried to fix it but I don't know JS.

Cheers!

**Comment by dzaima** [comment]
It's a regular backtick. The tip would have to show just `` ` ``, which is kind of redundant (though maybe it'd make it more clear that it's a regular character)

**Comment by mlochbaum** [comment]
The input hints are auto-generated from the keymap, so they're sure to align with the actual shortcuts at least. As to whether to add a hint with just `` ` ``, I can't tell whether that makes things more or less clear. Adding a hint on every key sounds sort of confusing; adding one for just `` ` `` is more natural, but because it's inconsistent you can't figure out what's going on by comparing it to other hovertexts.

**Comment by miguelraz** [comment]
Derp, I didn't even notice it wasn't a special character. I guess I wasn't too trusting after the Self ~ thingy looks higher up. At any rate, feel free to close.

**Comment by mlochbaum** [comment]
The `⋆`-not-asterisk thing also doesn't inspire confidence. Those accent characters are definitely troublesome, especially given that `` ` `` can be harder to type on various European keyboards. A hint on the documentation page probably makes sense at least; I'll keep thinking.
