### ISSUE TITLE
Macron not explained in expressions tutorial

### ISSUE THREAD

**Issue by gitonthescene** [mlochbaum/BQN#65]
I apologize if this is not the place for this type of commentary.  Feel free to redirect me as appropriate.

I noticed that the use of a macron for a minus sign goes unexplained in the [Expressions tutorial](https://mlochbaum.github.io/BQN/tutorial/expression.html) (unless I missed it.  I did a few searches).  For people coming from APL this isn’t a problem but depending on the target audience perhaps it deserves some mention.

I hope you find this observation useful.

Regards

**Comment by gitonthescene** [comment]
Also, should this be “are applied to 3”?

> Even worse, +˜ ÷ 3 looks just like +∘ ÷ 3, but it's two functions +˜ and ÷ applied to 3 while the version with Atop is a single function +∘÷ applied to 3. 

FWIW, I’m a slow reader and so I get tripped up easily.  I’m trying to turn it into a positive.

**Comment by mlochbaum** [comment]
Very good point about `¯`. I suppose I missed it because I didn't use it in source code there, but it should be explained in the first tutorial. It does get a mention on [this documentation page](https://mlochbaum.github.io/BQN/doc/arithmetic.html) (search for "high minus").

For the second point, I think this is fine: I'm saying the expression consists of functions applied to arguments. Note that "it's" has the apostrophe, making it "it is", not possessive.
