### ISSUE TITLE
Request for flashy examples in docs

### ISSUE THREAD

**Issue by qpwo** [mlochbaum/BQN#72]
> Tutorials assume (pretty presumptively, really. Disgusting.) that you are already motivated to learn BQN and use simple rather than flashy examples. Documents to induce motivation beyond the README are not yet available.

I'm one of those people who is you know curious but cautious and I need to see bit of beauty to really dig in. Would love to see some wild examples. In particular, the slides in this section of [Aaron Hsu's talk](https://youtu.be/z8MVKianh54?t=2408) struck me and I'd like to learn them in BQN (I don't know APL)

<img width="643" alt="image" src="https://user-images.githubusercontent.com/10591373/175445471-e411763c-f204-4bc8-aa7e-de183d40a6ab.png">

**Comment by mlochbaum** [comment]
It's been a while since I wrote that and it's much less accurate now. The [community page](https://mlochbaum.github.io/BQN/community/index.html) links to BQN examples: the most structured are probably Asher's videos, and Rosetta Code and Stack Exchange have a lot of good explanations for small programs.

Aaron's examples mostly translate fine to BQN, although set functions `∪∩~` aren't single primitives so they have to be changed a little. To be honest I don't like these snippets too much (the depth vector one is O(n³); I don't think you'd ever want to construct that matrix). But I do have a [documentation section](https://mlochbaum.github.io/BQN/doc/order.html#ordinals) on the `⍋⍋` pattern that he mentions.

APL                         | BQN                              | Alternative
----------------------------|----------------------------------|--------------
`2\|+⌿¨⍳12 12`              | `2\|+´¨↕12‿12`                   | `≠⌜˜2\|↕12`
`∘.(≢∪~∩)⍨(⌊∘⊃∪⊢)\⌽⍋⍋⌽d`    | ``(+´·¬∊∾∊˜)⌜˜(⍷⌊`⌾⌽)¨1↓↑⌽⍋⍋⌽d`` | ``((+´≠)⌜˜≠↑⟜(⊢<∞«⌊`⌾⌽)¨1↓↑)d``
`(⍳×/s)≡I∘⍋⍨⍋⍋,+⌿¨1+⍳s`     | `(↕×´s)≡⊏⟜⍋⍋⍋⥊+´¨1+↕s`           |

**Comment by qpwo** [comment]
Thank you!
