### ISSUE TITLE
0⊸↕·⋄{0} results in nonsensical behavior

### ISSUE THREAD

**Issue by wooosh** [mlochbaum/BQN#98]
Both CBQN and and the JS implementation break on this input:

CBQN:
```
$ bqn --version
CBQN 0.7.0
built with FFI, singeli x86-64
$ echo "0⊸↕·⋄{0}" | bqn
   Error: VM compiler: Stack size goes negative
```

[JS:](https://mlochbaum.github.io/BQN/try.html#code=MOKKuOKGlcK3CnswfQ==) 
```
Invalid left-hand side in assignment
```
![image](https://github.com/mlochbaum/BQN/assets/12696312/140e7dd3-d614-4e99-a6f4-33a1f2aed538)

**Comment by dzaima** [comment]
simpler repos: `0⊸0 · ⋄ 0`, `0¨ · ⋄ 0`

**Comment by mlochbaum** [comment]
Here the modifier bytecode and drop instruction fell in the same target location, and the ordering that ends up breaking ties ended up giving the wrong result. I've reordered them so drop is near the end. The issue can show up with subexpressions like `(0¨·)⊢1` in addition to `·⋄` and this is also fixed.

Moving drop past several other kinds of bytecode could conceivably break other cases. I think the original ordering was just because functions and modifiers had to be at the end for source code tracking (now there are magic indices, sadly), and none of the types `dr` is moved past look suspicious. I also did a quick check with test/unit.bqn by running both the old and new bytecode ordering within the compiler and confirmed that the only difference is in the test added for this issue.
